# Makefile for the USM player ( WATCOM C Version )
# It can be use by borland make.exe and watcom wmake.exe
#
# (c) 1996 FreddyV/Useless

TARGET = play.exe

# USM play lib file
LIB   = ..\LIB\usmppmw.lib
#LIB   = ..\LIB\usmpd4g.lib

# USM play include files directory
INC   = ..\SRC

# WATCOM C include directory
CINC  = ..\..\WATCOM\H

# PMODE/W or DOS/4GW Extender (Change also the ASMPARAM section)
SYSTEM = pmodew
#SYSTEM = dos4g

#-----------------------------------------------------------------------------

# C compiler parameters
# ---------------------
#

CPARAM   = -i=$(CINC) -i=$(INC) -s

ASM      = TASM $(ASMPARAM)
C        = WPP386
LINK     = WLINK

OBJLIST     = play.obj

#
#                       ** Files link **
#

$(TARGET)   : $(OBJLIST)
                $(LINK) @WATCOM.LNK file play file $(LIB) system $(SYSTEM) name $(TARGET)
#     pmwlite /c4 $(TARGET)

play.obj    : play.cpp $(INC)\usmplay.h
                $(C) $(CPARAM) play.cpp
