;            ษอออออออออออออออออออออออออออออออออออออออออออออออออออป
;            บ     ๗๗๗๗๗๗๗๗๗๗๗๗๗๗ LDEBUG.INC ๗๗๗๗๗๗๗๗๗๗๗๗๗๗      บ
;            บ                                                   บ
;            บ                  Loader Debugger                  บ
;            บฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤบ
;            บ   By Freddy Vtel (FreddyV/Useless)              บ
;            บ                                                   บ
;            บ   Code Starts .................. 06/04/1996       บ
;            บ   Last Update .................. 08/05/1996       บ
;            ศอออออออออออออออออออออออออออออออออออออออออออออออออออผ

Global Print_Header      :Near
Global Print_Sample      :Near
Global Print_Instruments :Near

; LDEBUG.INC (c) 1997 FreddyV/Useless